test:
  api_token: test_key
  search_server: 'http://test.te'
  data_server: 'http://test2.te'
  pulse_server: 'http://test.te/'
  marker: 12346
  bitly:
    hello: 'world'

development:
  api_token: test_key
  search_server: 'http://test.te'
  data_server: 'http://beta-overmind.jetradar.com'
  pulse_server: 'http://test.te/'
  marker:
